// Node built-in test runner. Run from the package root with:
//   node --test test/pr-body.test.mjs
//
// The attribution footer was duplicated verbatim in eleven pull request bodies and
// pointed at a path that had moved, so every PR the tool opened carried a dead link.
// These assertions exist so the link cannot rot in one body while staying correct in
// the others.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  autoGeneratedFooter,
  RELEASE_MANAGEMENT_MCP_URL,
} from "../lib/git-flow.js";

const srcDir = join(dirname(dirname(fileURLToPath(import.meta.url))), "src");

test("the footer points at the package's real location", () => {
  assert.equal(
    RELEASE_MANAGEMENT_MCP_URL,
    "https://github.com/officespacesoftware/versioner/tree/master/js/packages/release-management-mcp"
  );
  assert.match(autoGeneratedFooter(), /^🤖 Auto-generated by \[Release Management MCP\]\(https:\/\/\S+\)$/);
});

test("no source file hardcodes an attribution footer", () => {
  const offenders = [];
  for (const file of readdirSync(srcDir).filter((f) => f.endsWith(".ts"))) {
    const contents = readFileSync(join(srcDir, file), "utf8");
    for (const [index, line] of contents.split("\n").entries()) {
      // The helper's own definition is the one permitted occurrence.
      const isDefinition = line.includes("${RELEASE_MANAGEMENT_MCP_URL}");
      if (line.includes("Auto-generated by [Release Management MCP]") && !isDefinition) {
        offenders.push(`${file}:${index + 1}`);
      }
    }
  }
  assert.deepEqual(
    offenders,
    [],
    `these lines should call autoGeneratedFooter() instead: ${offenders.join(", ")}`
  );
});

test("the stale pre-consolidation path appears nowhere in source", () => {
  const offenders = [];
  for (const file of readdirSync(srcDir).filter((f) => f.endsWith(".ts"))) {
    if (readFileSync(join(srcDir, file), "utf8").includes("tree/main/release-management-mcp")) {
      offenders.push(file);
    }
  }
  assert.deepEqual(offenders, []);
});
